#!/bin/sh
set -e
# litestream-wrapper.sh — entrypoint for the litestream sidecar container.
# Starts Litestream and watches a sentinel file for config reload signals
# written by the app's LitestreamConfigSyncService.

CONFIG=/app/db/litestream.yml
SENTINEL=/app/db/.litestream-reload
LITESTREAM_PID=""

# Clean shutdown: forward signals to the litestream process
cleanup() {
    echo "Shutting down Litestream..."
    if [ -n "$LITESTREAM_PID" ]; then
        kill "$LITESTREAM_PID" 2>/dev/null || true
        wait "$LITESTREAM_PID" 2>/dev/null || true
    fi
    exit 0
}
trap cleanup INT TERM

# Wait for the config file to be generated by the app
echo "Litestream sidecar starting..."
echo "Waiting for config at $CONFIG ..."
while [ ! -f "$CONFIG" ]; do
    sleep 5
    echo "  still waiting for $CONFIG ..."
done
echo "Config found. Starting Litestream replication."

# Start litestream in background
litestream replicate -config "$CONFIG" &
LITESTREAM_PID=$!
echo "Litestream started (PID $LITESTREAM_PID)"

# Watch for config reload signal
# Initialize from existing sentinel so we don't restart immediately on boot
if [ -f "$SENTINEL" ]; then
    LAST_RELOAD=$(cat "$SENTINEL")
else
    LAST_RELOAD=""
fi
while true; do
    if [ -f "$SENTINEL" ]; then
        CURRENT=$(cat "$SENTINEL")
        if [ "$CURRENT" != "$LAST_RELOAD" ]; then
            echo "Config reload requested, restarting Litestream..."
            kill "$LITESTREAM_PID" 2>/dev/null || true
            wait "$LITESTREAM_PID" 2>/dev/null || true
            litestream replicate -config "$CONFIG" &
            LITESTREAM_PID=$!
            echo "Litestream restarted (PID $LITESTREAM_PID)"
            LAST_RELOAD="$CURRENT"
        fi
    fi
    sleep 10
done
