#!/bin/sh
# litestream-wrapper.sh — entrypoint for the litestream sidecar container.
# Starts Litestream and watches a sentinel file for config reload signals
# written by the app's LitestreamConfigSyncService.

CONFIG=/app/db/litestream.yml
SENTINEL=/app/db/.litestream-reload

# Wait for the config file to be generated by the app
echo "Waiting for Litestream config at $CONFIG ..."
while [ ! -f "$CONFIG" ]; do
    sleep 5
done
echo "Config found. Starting Litestream."

# Start litestream in background
litestream replicate -config "$CONFIG" &
LITESTREAM_PID=$!

# Watch for config reload signal
LAST_RELOAD=""
while true; do
    if [ -f "$SENTINEL" ]; then
        CURRENT=$(cat "$SENTINEL")
        if [ "$CURRENT" != "$LAST_RELOAD" ]; then
            echo "Config reload requested, restarting Litestream..."
            kill $LITESTREAM_PID 2>/dev/null
            wait $LITESTREAM_PID 2>/dev/null
            litestream replicate -config "$CONFIG" &
            LITESTREAM_PID=$!
            LAST_RELOAD="$CURRENT"
        fi
    fi
    sleep 10
done
